<?php
namespace console\controllers;

use Yii;
use yii\base\DynamicModel;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Request;
use yii\helpers\Json;
use yii\data\ArrayDataProvider;
use yii\console\Controller;			
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use console\models\Cronjob;
class RekapAbsensiController extends Controller
{
    public function behaviors()
    {
        return [
			'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ]
        ];
    }

	/**===================
	 *  DAILY  TRANSAKSI
	 * ===================
	*/
	public function actionRunDaily(){
		$tgl1='2017-09-23';
		$tgl2='2017-10-22';
		//'".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."'
		//'".$tgl1."' AND '".$tgl2."'
		$model = Cronjob::find()->where(['TABEL'=>'REKAP_ABSEN','STT'=>1])->all();		
		foreach ($model as $row => $val){
			//$rslt[]=$val['TABEL'];		
			$sqlstr1="
				INSERT INTO hrd_absen_rekap(
					ID,ACCESS_GROUP,STORE_ID,KARYAWAN_ID,
					TGL,WAKTU_MASUK,WAKTU_KELUAR,SHIFT_ID,SHIFT_NM,SHIFT_IN,SHIFT_OUT,SHIFT_TELAT,SHIFT_PULANG,SHIFT_RADIUS,SELISIH_TELAT,SELISIH_AWALPULANG,KELEBIHAN_WAKTU,TTL_MASUK,
					IZIN_STT,IZIN_STT_NM,IZIN,IZIN_NM,
					MASUK_LAT,MASUK_LAG,MASUK_RADIUS,PULANG_LAT,PULANG_LAG,PULANG_RADIUS,
					POT_PERSEN_TELAT,POT_RUPIAH_TELAT,POT_JAM_TELAT,
					POT_PERSEN_PULANG,POT_RUPIAH_PULANG,POT_JAM_PULANG,
					LEMBUR_PERSEN,LEMBUR_RUPIAH,LEMBUR_JAM,
					ID_TELAT,ID_AWALPULANG,ID_LEMBUR,
					IN_ABSENID,OUT_ABSENID,
					IN_SEQ,SEQ_SHIFT
				)
				SELECT 
					#=============================================================
					#== RESULT QUERY (INSERT/UPDATE) to TABLE (hrd_absen_rekap) ==
					#== REMEMBER, JIKA TANGGAL TIDAK ADA MAKA DIANGAP ALFA.     ==
					#========================================	====================
					#ID VALIDASI (INSERT/UPDATE)
					g1.ID,
					#GROUP PENCARIAN DATA 
					f1.ACCESS_GROUP,f1.STORE_ID,f1.KARYAWAN_ID,#f1.KARYAWAN,
					#== PERSENSI (MASUK/PULANG)TANGGAL & JAM
					f1.TGL,f1.WAKTU_MASUK,f1.WAKTU_KELUAR,
					#=SHIFT PROPERTY
					f1.SHIFT_ID,f1.SHIFT_NM,f1.SHIFT_IN,f1.SHIFT_OUT,f1.SHIFT_TELAT,f1.SHIFT_PULANG,f1.RADIUS AS SHIFT_RADIUS,	
					#=KALULATE SELISIH POTONGAN & LEMBURAN
					f1.SELISIH_TELAT,f1.SELISIH_AWALPULANG,f1.KELEBIHAN_WAKTU,f1.TTL_MASUK,
					#IZIN PROPERTY, IZIN TABLE IZIN_STT(0) adalah IZIN Tidak Dibayar; IZIN_STT(1) adalah IZIN Dibayar; untuk absensi harian)
					f1.IZIN_STT,f1.IZIN_STT_NM,f1.IZIN,f1.IZIN_NM,
					#=PERSENSI PROPERTY, UNTUK VALIDATION POSITIONIG GPS
					f1.MASUK_LAT,f1.MASUK_LAG,'' AS MASUK_RADIUS, f1.PULANG_LAT,f1.PULANG_LAG,'' AS PULANG_RADIUS,
					#ENABLE/DISABLE POTONGAN
					#f1.ACTIVE_TELAT,f1.ACTIVE_PULANG,f1.ACTIVE_IZIN,		
					f2.POT_PERSEN AS POT_PERSEN_TELAT,f2.POT_RUPIAH AS POT_RUPIAH_TELAT,f2.POT_JAM2 AS POT_JAM_TELAT,
					f3.POT_PERSEN AS POT_PERSEN_PULANG,f3.POT_RUPIAH AS POT_RUPIAH_PULANG,f3.POT_JAM2 AS POT_JAM_PULANG,
					f4.POT_PERSEN AS LEMBUR_PERSEN,f4.POT_RUPIAH AS LEMBUR_RUPIAH,f4.POT_JAM2 AS LEMBUR_JAM,
					#UPAH KARYAWAN DALAM HARIAN
					#f1.UPAH_HARIAN,
					#JOIN TBL hrd_setting_pot; ID_TELAT (STT_POTONGAN=0)& D_AWALPULANG (STT_POTONGAN=1).
					f1.ID_TELAT,f1.ID_AWALPULANG,    
					#UNTUK JOIN/POST/GET hrd_absen_img (IN/OUT IMAGE)
					f1.IN_ABSENID,f1.OUT_ABSENID,f1.ID_LEMBUR,
					#VALIDASI TANGGAL MASUK DAN TANGGAL KELUAR (N_SEQ=SEQUENT TGL ABSEN;SEQ_SHIFT=EQUENT TGL SETTING ABSEN)
					f1.IN_SEQ,f1.SHIFT_SEQ
				FROM
				(
					SELECT
						#========================================
						#== Pencarian id Potongan dan lemburan ==
						#========================================						
						#=AMBIL ID UNTUK POTONGAN TELAT STT_POTONGAN='0'
						(SELECT ID FROM hrd_setting_pot 
						 WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."' AND STT_POTONGAN='0' AND #SHIFT_ID=e1.SHIFT_ID AND
										 (time(e1.SELISIH_TELAT) BETWEEN time(POT_JAM1) AND time(POT_JAM2))                               									
								ORDER BY POT_JAM2 DESC LIMIT 1
						) AS ID_TELAT,
						#=AMBIL ID UNTUK POTONGAN PULANG STT_POTONGAN='1'
						(SELECT ID FROM hrd_setting_pot 
						 WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."' AND STT_POTONGAN='1' AND #SHIFT_ID=e1.SHIFT_ID AND
									(time(e1.SELISIH_AWALPULANG) BETWEEN time(POT_JAM1) AND time(POT_JAM2))
						 ORDER BY POT_JAM2 DESC LIMIT 1
						) AS ID_AWALPULANG,
						#=AMBIL ID UNTUK  LEMBURAN TT_POTONGAN='2'
						(SELECT ID FROM hrd_setting_pot 
						 WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."' AND STT_POTONGAN='2' AND #SHIFT_ID=e1.SHIFT_ID AND
									(time(e1.KELEBIHAN_WAKTU) BETWEEN time(POT_JAM1) AND time(POT_JAM2))
						 ORDER BY POT_JAM2 DESC LIMIT 1
						) AS ID_LEMBUR,						
						#=KALULATE SELISIH POTONGAN & LEMBURAN
						e1.SELISIH_TELAT,e1.SELISIH_AWALPULANG,e1.KELEBIHAN_WAKTU,e1.TTL_MASUK,
						#=SHIFT PROPERTY & PERSENSI PROPERTY
						e1.SHIFT_ID,e1.SHIFT_NM,e1.WAKTU_MASUK,e1.WAKTU_KELUAR,e1.SHIFT_IN,e1.SHIFT_OUT,e1.SHIFT_TELAT,e1.SHIFT_PULANG,
						#=IZIN PROPERTY
						e1.IZIN_STT,e1.IZIN_STT_NM,e1.IZIN,e1.IZIN_NM,
						#=PERSENSI PROPERTY, UNTUK VALIDATION POSITIONIG GPS
						e1.MASUK_LAT,e1.MASUK_LAG,e1.PULANG_LAT,e1.PULANG_LAG,e1.RADIUS,
						#=KEY VALIDATION UNTUK PENCARIAN
						e1.IN_ABSENID,e1.OUT_ABSENID,e1.ACCESS_GROUP,e1.STORE_ID,e1.KARYAWAN_ID,e1.IN_SEQ,e1.SHIFT_SEQ,e1.TGL
					FROM
					(
						SELECT 
							#=====================================================================
							#== UNTUK AKUMULSI WAKTU SHIFT & PERSENSI BERDASARKAN SELISIH WAKTU ==
							#=====================================================================
							#=HITUNG SELISIH TELAT
							(CASE WHEN d1.WAKTU_MASUK <>''  AND d1.WAKTU_KELUAR <>'' AND TIME(d1.SHIFT_TELAT)<=TIME(SEC_TO_TIME(TIMESTAMPDIFF(SECOND,d1.SHIFT_IN,d1.WAKTU_MASUK))) THEN 
								SEC_TO_TIME(TIMESTAMPDIFF(SECOND,d1.SHIFT_IN,d1.WAKTU_MASUK))
							ELSE NULL END) AS SELISIH_TELAT,
							#=HITUNG SELISIH PULANG CEPAT
							(CASE WHEN d1.WAKTU_MASUK <>''  AND d1.WAKTU_KELUAR <>'' AND (d1.WAKTU_KELUAR < d1.SHIFT_OUT) THEN
								SEC_TO_TIME(TIMESTAMPDIFF(SECOND,d1.SHIFT_OUT,d1.WAKTU_KELUAR))
							ELSE NULL END) AS SELISIH_AWALPULANG,
							##=HITUNG SELISIH KELEBIHAN WAKTU
							(CASE WHEN d1.WAKTU_MASUK <>''  AND d1.WAKTU_KELUAR <>'' AND (time(d1.TTL_MASUK) > time(d1.TTL_SHIFT)) THEN 
								SEC_TO_TIME(TIMESTAMPDIFF(SECOND,d1.TTL_SHIFT,d1.TTL_MASUK)) ELSE NULL END) AS KELEBIHAN_WAKTU,
							#==TOTAL JAM MASUK KERJA
							d1.TTL_MASUK,
							#=SHIFT PROPERTY & PERSENSI PROPERTY
							d1.WAKTU_MASUK,d1.WAKTU_KELUAR,d1.SHIFT_IN,d1.SHIFT_OUT,d1.SHIFT_TELAT,d1.SHIFT_PULANG,d1.SHIFT_ID,d1.SHIFT_NM,
							#=IZIN PROPERTY
							d1.IZIN_STT,d1.IZIN_STT_NM,d1.IZIN,d1.IZIN_NM,
							#=PERSENSI PROPERTY, UNTUK VALIDATION POSITIONIG GPS
							d1.MASUK_LAT,d1.MASUK_LAG,d1.PULANG_LAT,d1.PULANG_LAG,d1.RADIUS,
							#=KEY VALIDATION UNTUK PENCARIAN
							d1.IN_ABSENID,d1.OUT_ABSENID,d1.ACCESS_GROUP,d1.STORE_ID,d1.KARYAWAN_ID,d1.IN_SEQ,d1.SHIFT_SEQ,d1.TGL
						FROM
						(
							SELECT
								#==============================================================
								#== UNTUK AKUMULSI WAKTU SHIFT & PERSENSI BERDASARKAN SEQWEN ==
								#==============================================================
								#=JAM MASUK/KELUAR DENGAN PENAMBAHAN TANGGAL DAN SEQUWEN 
								(CASE WHEN c1.WAKTU_MASUK<>'' OR c1.WAKTU_MASUK IS NOT NULL THEN CONCAT(c1.TGL,' ',c1.WAKTU_MASUK) ELSE NULL END) AS WAKTU_MASUK,
								(CASE WHEN c1.WAKTU_KELUAR<>'' OR c1.WAKTU_KELUAR IS NOT NULL THEN CONCAT(DATE_ADD(c1.TGL, INTERVAL c1.IN_SEQ DAY),' ',c1.WAKTU_KELUAR) ELSE NULL END) AS WAKTU_KELUAR,
								CONCAT(c1.TGL,' ',c2.SHIFT_IN) AS SHIFT_IN, CONCAT(DATE_ADD(c1.TGL, INTERVAL c1.IN_SEQ DAY),' ',c2.SHIFT_OUT) AS SHIFT_OUT,
								#=TOLERASI TELAT/PULANG LEBIH AWAL 
								CONCAT('00:',LPAD(c2.TOLERANSI_TELAT, 2, '0'),':00') AS SHIFT_TELAT,
								CONCAT('00:',LPAD(c2.TOLERANSI_PULANG, 2, '0'),':00') AS SHIFT_PULANG,
								#=TOTAL JAM PERSENSI KARYAWAN
								SEC_TO_TIME(TIMESTAMPDIFF(SECOND,
									CONCAT(c1.TGL,' ',c1.WAKTU_MASUK),
									CONCAT(DATE_ADD(c1.TGL, INTERVAL c1.IN_SEQ DAY),' ',c1.WAKTU_KELUAR))
								) AS TTL_MASUK,
								#=TOTAL JAM PER-SHIFT
								c2.RENTANG_TENGAH AS TTL_SHIFT,
								#=SHIFT PROPERTY
								c2.SHIFT_ID,c2.SHIFT_NM,
								#=IZIN PROPERTY
								c1.IZIN_STT,c1.IZIN_STT_NM,c1.IZIN,c1.IZIN_NM,
								#=PERSENSI PROPERTY, UNTUK VALIDATION POSITIONIG GPS
								c1.MASUK_LAT,c1.MASUK_LAG,c1.PULANG_LAT,c1.PULANG_LAG,c2.RADIUS,
								#=KEY VALIDATION UNTUK PENCARIAN
								c1.IN_ABSENID,c1.OUT_ABSENID,c1.ACCESS_GROUP,c1.STORE_ID,c1.KARYAWAN_ID,c1.IN_SEQ,SHIFT_SEQ,c1.TGL
							FROM
							(
								SELECT
									b2.KARYAWAN_ID,b2.ACCESS_GROUP,b2.STORE_ID,
									(CASE WHEN b2.IN_ABSENID IS NOT NULL THEN b2.IN_ABSENID ELSE '0' END) AS IN_ABSENID,
									(CASE WHEN b2.OUT_ABSENID IS NOT NULL THEN b2.OUT_ABSENID ELSE '0' END) AS OUT_ABSENID,										
									b2.TGL,b2.WAKTU_MASUK,b2.WAKTU_KELUAR,(CASE WHEN b2.WAKTU_MASUK >= b2.WAKTU_KELUAR THEN 1 ELSE 0 END) AS IN_SEQ,
									b2.IZIN,b2.IZIN_NM,b2.IZIN_STT,b2.IZIN_STT_NM,b2.MASUK_LAT,b2.MASUK_LAG,b2.PULANG_LAT,b2.PULANG_LAG
								FROM
								 ( SELECT 								
										 a1.ACCESS_GROUP,a1.STORE_ID,a1.KARYAWAN_ID,a1.TGL,a1.WAKTU_MASUK,a1.WAKTU_KELUAR,IN_ABSENID,OUT_ABSENID,
										 MAX(CASE WHEN a1.LOG='IZIN' THEN a1.IZIN_LOG ELSE '0' END) AS IZIN,
										 MAX(CASE WHEN a1.LOG='IZIN' THEN a1.LOG_NM ELSE 'NORMAL' END) AS IZIN_NM,
										 MAX(CASE WHEN a1.LOG='IZIN' THEN a1.IZIN_STT ELSE 0 END) AS IZIN_STT,
										 MAX(CASE WHEN a1.LOG='IZIN' THEN a1.IZIN_STT_NM ELSE 'NORMAL' END) AS IZIN_STT_NM,
										 MIN(CASE WHEN a1.LOG=0 THEN a1.LAT END) AS MASUK_LAT,MIN(CASE WHEN a1.LOG=0 THEN a1.LAG END) AS MASUK_LAG,
										 MIN(CASE WHEN a1.LOG=1 THEN a1.LAT END) AS PULANG_LAT,MIN(CASE WHEN a1.LOG=1 THEN a1.LAG END) AS PULANG_LAG
									FROM
									 (
										(
											SELECT ABSEN_ID,ACCESS_GROUP,STORE_ID,KARYAWAN_ID,
														(CASE WHEN STATUS=0 THEN ABSEN_ID END) AS IN_ABSENID,
													(CASE WHEN STATUS=1 THEN ABSEN_ID END) AS OUT_ABSENID,
														TGL,
														(CASE WHEN STATUS=0 THEN MIN(WAKTU) ELSE NULL END) WAKTU_MASUK,
														MAX(CASE WHEN STATUS=1 THEN WAKTU ELSE NULL END) WAKTU_KELUAR,
														STATUS AS LOG,'ABSEN' AS IZIN_LOG,
														(CASE WHEN STATUS=0 THEN 'IN' ELSE 'OUT' END) AS LOG_NM, '0' AS IZIN_STT,'NORMAL' AS IZIN_STT_NM,
														LATITUDE AS LAT,LONGITUDE AS LAG
											FROM hrd_absen
											WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND 
													STORE_ID='".$val['STORE_ID']."' AND
													(TGL BETWEEN '".$tgl1."' AND '".$tgl2."')
											GROUP BY ACCESS_GROUP,STORE_ID,KARYAWAN_ID,TGL
											ORDER BY STATUS ASC
										) 
										UNION 
										(
											SELECT '0' AS ABSEN_ID,x1.ACCESS_GROUP,x1.STORE_ID,x1.KARYAWAN_ID,
													 '' as IN_ABSENID,'' AS OUT_ABSENID,
													x1.TGL,x1.WAKTU AS WAKTU_MASUK,NULL AS WAKTU_KELUAR,
													'IZIN' AS LOG,x1.IZIN_ID AS IZIN_LOG,
													x1.IZIN_NM AS LOG_NM, x1.IZIN_STT,x1.IZIN_STT_NM,'0,0' AS LAT,'0,0' AS LAG
											FROM hrd_absen_izin x1
											WHERE x1.ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND 
													x1.STORE_ID='".$val['STORE_ID']."' AND
													#x1.KARYAWAN_ID='".$val['STORE_ID'].".0001' AND
													(x1.TGL BETWEEN '".$tgl1."' AND '".$tgl2."') 
										) 
									) a1
									GROUP BY a1.ACCESS_GROUP,a1.STORE_ID,a1.KARYAWAN_ID,a1.TGL
								) b2 
							) c1 
							LEFT JOIN 
							(
								SELECT 
									ACCESS_GROUP,STORE_ID,SHIFT_ID,SHIFT_NM,
									RENTANG_BAWAH,RENTANG_ATAS,RENTANG_TENGAH,
									SHIFT_IN_BATAS_BAWAH,SHIFT_IN_BATAS_ATAS,SHIFT_IN_BATAS_SEQ,
									SHIFT_IN,SHIFT_SEQ,SHIFT_OUT,
									RADIUS_KOORDINAT AS RADIUS,TOLERANSI_TELAT,TOLERANSI_PULANG
								FROM hrd_setting_jamkerja
								WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."' 
							) c2 on c2.ACCESS_GROUP=c1.ACCESS_GROUP AND c2.STORE_ID=c1.STORE_ID AND 
								(
									CONCAT(c1.TGl,' ',c1.WAKTU_MASUK) BETWEEN 
									CONCAT(DATE_SUB(c1.TGl, INTERVAL SHIFT_IN_BATAS_SEQ DAY),' ',c2.SHIFT_IN_BATAS_BAWAH) AND 
									CONCAT(c1.TGl,' ',c2.SHIFT_IN_BATAS_ATAS)
								)									
						) d1 
					) e1
				) f1 
				LEFT JOIN hrd_setting_pot f2 ON f2.ID=f1.ID_TELAT
				LEFT JOIN hrd_setting_pot f3 ON f3.ID=f1.ID_AWALPULANG
				LEFT JOIN hrd_setting_pot f4 ON f4.ID=f1.ID_LEMBUR
				LEFT JOIN 
				(
					SELECT DISTINCT * FROM hrd_absen_rekap 
					WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."' 
				)g1 ON g1.ACCESS_GROUP=f1.ACCESS_GROUP AND g1.STORE_ID=f1.STORE_ID AND g1.KARYAWAN_ID=f1.KARYAWAN_ID AND g1.TGL=f1.TGL
				ON DUPLICATE KEY UPDATE
				WAKTU_MASUK=f1.WAKTU_MASUK,WAKTU_KELUAR=f1.WAKTU_KELUAR,SHIFT_ID=f1.SHIFT_ID,SHIFT_NM=f1.SHIFT_NM,SHIFT_IN=f1.SHIFT_IN,SHIFT_OUT=f1.SHIFT_OUT,
				SHIFT_TELAT=f1.SHIFT_TELAT,SHIFT_PULANG=f1.SHIFT_PULANG,SHIFT_RADIUS=f1.RADIUS,SELISIH_TELAT=f1.SELISIH_TELAT,
				SELISIH_AWALPULANG=f1.SELISIH_AWALPULANG,KELEBIHAN_WAKTU=f1.KELEBIHAN_WAKTU,IZIN_STT=f1.IZIN_STT,IZIN_STT_NM=f1.IZIN_STT_NM,IZIN=f1.IZIN,IZIN_NM=f1.IZIN_NM,
				MASUK_LAT=f1.MASUK_LAT,MASUK_LAG=f1.MASUK_LAG,MASUK_RADIUS='',PULANG_LAT=f1.PULANG_LAT,PULANG_LAG=f1.PULANG_LAG,PULANG_RADIUS='',
				POT_PERSEN_TELAT=f2.POT_PERSEN,POT_RUPIAH_TELAT=f2.POT_RUPIAH,POT_JAM_TELAT=f2.POT_JAM2,
				POT_PERSEN_PULANG=f3.POT_PERSEN,POT_RUPIAH_PULANG=f3.POT_RUPIAH,POT_JAM_PULANG=f3.POT_JAM2,
				LEMBUR_PERSEN=f4.POT_PERSEN,LEMBUR_RUPIAH=f4.POT_RUPIAH,LEMBUR_JAM=f4.POT_JAM2,
				ID_TELAT=f1.ID_TELAT,ID_AWALPULANG=f1.ID_AWALPULANG,ID_LEMBUR=f1.ID_LEMBUR,
				IN_ABSENID=f1.IN_ABSENID,OUT_ABSENID=f1.OUT_ABSENID,IN_SEQ=f1.IN_SEQ,SEQ_SHIFT=f1.SHIFT_SEQ				
			";
			Yii::$app->db->createCommand($sqlstr1)->execute();
			//==UPDATE==
			$modelUpdate = Cronjob::find()->where(['TABEL'=>$val['TABEL'],'ACCESS_GROUP'=>$val['ACCESS_GROUP'],'STORE_ID'=>$val['STORE_ID']])->one();
			$modelUpdate->STT=0;
			$modelUpdate->UPDATE_CRONJOB=$val['UPDATE_TABEL'];;
			$modelUpdate->save();			
		};
	}
	
	/**===================
	 *  DAILY  TRANSAKSI
	 * ===================
	*/
	public function actionRunDailyX(){
		$tgl1='2017-09-23';
		$tgl2='2017-10-22';
		//'".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."'
		//'".$tgl1."' AND '".$tgl2."'
		$model = Cronjob::find()->where(['TABEL'=>'REKAP_ABSEN','STT'=>1])->all();		
		foreach ($model as $row => $val){
			//$rslt[]=$val['TABEL'];		
			$sqlstr1="
					#======================================
					# REKAP ABSENSI KARYAWAN (IN/OUT/IZIN)
					#======================================
					INSERT INTO hrd_absen_rekap(
					ID,ACCESS_GROUP,STORE_ID,KARYAWAN_ID,KARYAWAN,
					TGL,WAKTU_MASUK,WAKTU_KELUAR,SHIFT_ID,SHIFT_NM,SHIFT_IN,SHIFT_OUT,SHIFT_TELAT,SHIFT_PULANG,SHIFT_RADIUS,SELISIH_TELAT,SELISIH_AWALPULANG,KELEBIHAN_WAKTU,
					IZIN_STT,IZIN_STT_NM,IZIN,IZIN_NM,
					MASUK_LAT,MASUK_LAG,MASUK_RADIUS,PULANG_LAT,PULANG_LAG,PULANG_RADIUS,
					ACTIVE_TELAT,ACTIVE_PULANG,ACTIVE_IZIN,
					POT_PERSEN_TELAT,POT_RUPIAH_TELAT,POT_JAM_TELAT,
					POT_PERSEN_PULANG,POT_RUPIAH_PULANG,POT_JAM_PULANG,
					LEMBUR_PERSEN,LEMBUR_RUPIAH,LEMBUR_JAM,
					UPAH_HARIAN, 
					ID_TELAT,ID_AWALPULANG,   
					IN_ABSENID,OUT_ABSENID,
					IN_SEQ,SEQ_SHIFT,ID_LEMBUR
					)
					SELECT g1.ID,
						#REMEMBER, JIKA TANGGAL TIDAK ADA MAKA DIANGAP ALFA.
						#INFO BASIC KARYAWAN & TANGGAL ABSENSI
						f1.ACCESS_GROUP,f1.STORE_ID,f1.KARYAWAN_ID,f1.KARYAWAN,
						#ABSENSI TANGGAL & JAM
						f1.TGL,f1.WAKTU_MASUK,f1.WAKTU_KELUAR,
						#SHIFT SETTING
						f1.SHIFT_ID,f1.SHIFT_NM,f1.SHIFT_IN,f1.SHIFT_OUT,f1.SHIFT_TELAT,f1.SHIFT_PULANG,f1.RADIUS AS SHIFT_RADIUS,	
						#KALULATE ABSENSI
						f1.SELISIH_TELAT,f1.SELISIH_AWALPULANG,f1.KELEBIHAN_WAKTU,
						#IZIN TABLE IZIN_STT(1) adalah IZIN Tidak Dibayar; IZIN_STT(0) adalah IZIN Dibayar; untuk absensi harian)
						f1.IZIN_STT,f1.IZIN_STT_NM,f1.IZIN,f1.IZIN_NM,
						#VALIDATION POSITIONIG GPS
						f1.MASUK_LAT,f1.MASUK_LAG,'' AS MASUK_RADIUS, f1.PULANG_LAT,f1.PULANG_LAG,'' AS PULANG_RADIUS,
						#ENABLE/DISABLE POTONGAN
						f1.ACTIVE_TELAT,f1.ACTIVE_PULANG,f1.ACTIVE_IZIN,		
						f2.POT_PERSEN AS POT_PERSEN_TELAT,f2.POT_RUPIAH AS POT_RUPIAH_TELAT,f2.POT_JAM2 AS POT_JAM_TELAT,
						f3.POT_PERSEN AS POT_PERSEN_PULANG,f3.POT_RUPIAH AS POT_RUPIAH_PULANG,f3.POT_JAM2 AS POT_JAM_PULANG,
						f4.POT_PERSEN AS LEMBUR_PERSEN,f4.POT_RUPIAH AS LEMBUR_RUPIAH,f4.POT_JAM2 AS LEMBUR_JAM,
						#UPAH KARYAWAN DALAM HARIAN
						f1.UPAH_HARIAN,
						#JOIN TBL hrd_setting_pot; ID_TELAT (STT_POTONGAN=0)& D_AWALPULANG (STT_POTONGAN=1).
						f1.ID_TELAT,f1.ID_AWALPULANG,    
						#UNTUK JOIN/POST/GET hrd_absen_img (IN/OUT IMAGE)
						f1.IN_ABSENID,f1.OUT_ABSENID,
						#VALIDASI TANGGAL MASUK DAN TANGGAL KELUAR (N_SEQ=SEQUENT TGL ABSEN;SEQ_SHIFT=EQUENT TGL SETTING ABSEN)
						f1.IN_SEQ,f1.SHIFT_SEQ,f1.ID_LEMBUR
					FROM
					(
						SELECT
							e1.KARYAWAN,e1.WAKTU_MASUK,e1.WAKTU_KELUAR,e1.SHIFT_IN,e1.SHIFT_OUT,e1.SHIFT_TELAT,e1.SHIFT_PULANG,
							#POTONGAN TELAT STT_POTONGAN='0'
							(SELECT ID FROM hrd_setting_pot 
							 WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."' AND STT_POTONGAN='0' AND #SHIFT_ID=e1.SHIFT_ID AND
   							       (time(e1.SELISIH_TELAT) BETWEEN time(POT_JAM1) AND time(POT_JAM2))                               									
									ORDER BY POT_JAM2 DESC LIMIT 1
							) AS ID_TELAT,
							#POTONGAN PULANG STT_POTONGAN='1'
							(SELECT ID FROM hrd_setting_pot 
							 WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."' AND STT_POTONGAN='1' AND #SHIFT_ID=e1.SHIFT_ID AND
										(time(e1.SELISIH_AWALPULANG) BETWEEN time(POT_JAM1) AND time(POT_JAM2))
							 ORDER BY POT_JAM2 DESC LIMIT 1
							) AS ID_AWALPULANG,
							#LEMBURAN TT_POTONGAN='2'
							(SELECT ID FROM hrd_setting_pot 
							 WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."' AND STT_POTONGAN='2' AND #SHIFT_ID=e1.SHIFT_ID AND
										(time(e1.KELEBIHAN_WAKTU) BETWEEN time(POT_JAM1) AND time(POT_JAM2))
							 ORDER BY POT_JAM2 DESC LIMIT 1
							) AS ID_LEMBUR,
							e1.SHIFT_ID,e1.SHIFT_NM,
							#IZIN TITTLE
							e1.IZIN_STT,e1.IZIN_STT_NM,e1.IZIN,e1.IZIN_NM,
							#VALIDATION POSITIONIG GPS
							e1.MASUK_LAT,e1.MASUK_LAG,e1.PULANG_LAT,e1.PULANG_LAG,e1.RADIUS,
							#ENABLE/DISABLE POTONGAN
							e1.ACTIVE_TELAT,e1.ACTIVE_PULANG,e1.ACTIVE_IZIN,		
							#CALCULATE JUMLAH/PAYMENT
							e1.UPAH_HARIAN,    
							#e2.STT_POTONGAN,e2.POT_PERSEN,e2.POT_RUPIAH,POT_JAM,
							#KALULATE ABSENSI
							e1.SELISIH_TELAT,e1.SELISIH_AWALPULANG,e1.KELEBIHAN_WAKTU,
							#GROUP ID SEARCH VALIDATION
							e1.IN_ABSENID,e1.OUT_ABSENID,e1.ACCESS_GROUP,e1.STORE_ID,e1.KARYAWAN_ID,e1.IN_SEQ,e1.SHIFT_SEQ,e1.TGL
						FROM
						(
							SELECT 
								d1.KARYAWAN,d1.WAKTU_MASUK,d1.WAKTU_KELUAR,d1.SHIFT_IN,d1.SHIFT_OUT,d1.SHIFT_TELAT,d1.SHIFT_PULANG,d1.SHIFT_ID,d1.SHIFT_NM,
								#IZIN TITTLE
								d1.IZIN_STT,d1.IZIN_STT_NM,d1.IZIN,d1.IZIN_NM,
								#VALIDATION POSITIONIG GPS
								d1.MASUK_LAT,d1.MASUK_LAG,d1.PULANG_LAT,d1.PULANG_LAG,d1.RADIUS,
								#ENABLE/DISABLE POTONGAN
								d1.ACTIVE_TELAT,d1.ACTIVE_PULANG,d1.ACTIVE_IZIN,
								#CALCULATE JUMLAH/PAYMENT
								d1.UPAH_HARIAN,
								#KALULATE ABSENSI
								(CASE WHEN TIME(d1.SHIFT_TELAT)<=TIME(SEC_TO_TIME(TIMESTAMPDIFF(SECOND,d1.SHIFT_IN,d1.WAKTU_MASUK))) THEN 
									SEC_TO_TIME(TIMESTAMPDIFF(SECOND,d1.SHIFT_IN,d1.WAKTU_MASUK))
								ELSE '' END) AS SELISIH_TELAT,
								(CASE WHEN d1.WAKTU_KELUAR < d1.SHIFT_OUT THEN
									SEC_TO_TIME(TIMESTAMPDIFF(SECOND,d1.SHIFT_OUT,d1.WAKTU_KELUAR))
								ELSE '' END) AS SELISIH_AWALPULANG,
								#CALCULATE JUMLAH/PAYMENT
								(CASE WHEN time(d1.TTL_MASUK) > time(d1.TTL_SHIFT) THEN SEC_TO_TIME(TIMESTAMPDIFF(SECOND,d1.TTL_SHIFT,d1.TTL_MASUK)) ELSE '' END) AS KELEBIHAN_WAKTU,
								#GROUP ID SEARCH VALIDATION
								d1.IN_ABSENID,d1.OUT_ABSENID,d1.ACCESS_GROUP,d1.STORE_ID,d1.KARYAWAN_ID,d1.IN_SEQ,d1.SHIFT_SEQ,d1.TGL
							FROM
							(
								SELECT 
									c1.KARYAWAN,#c1.IN_SEQ,c2.SEQ AS SEQ_SHIFT,
									(CASE WHEN c1.WAKTU_MASUK IS NOT NULL THEN CONCAT(c1.TGL,' ',c1.WAKTU_MASUK) ELSE NULL END) AS WAKTU_MASUK,
									(CASE WHEN c1.WAKTU_KELUAR IS NOT NULL THEN CONCAT(DATE_ADD(c1.TGL, INTERVAL c1.IN_SEQ DAY),' ',c1.WAKTU_KELUAR) ELSE '' END) AS WAKTU_KELUAR,
									CONCAT(c1.TGL,' ',c2.SHIFT_IN) AS SHIFT_IN, CONCAT(DATE_ADD(c1.TGL, INTERVAL c1.IN_SEQ DAY),' ',c2.SHIFT_OUT) AS SHIFT_OUT,
									CONCAT('00:',LPAD(c2.TOLERANSI_TELAT, 2, '0'),':00') AS SHIFT_TELAT,CONCAT('00:',LPAD(c2.TOLERANSI_PULANG, 2, '0'),':00') AS SHIFT_PULANG,
									SEC_TO_TIME(TIMESTAMPDIFF(SECOND,
										CONCAT(c1.TGL,' ',c1.WAKTU_MASUK),
										CONCAT(DATE_ADD(c1.TGL, INTERVAL c1.IN_SEQ DAY),' ',c1.WAKTU_KELUAR))
									) AS TTL_MASUK,
									#SEC_TO_TIME(TIMESTAMPDIFF(SECOND,
									#	CONCAT(c1.TGL,' ',c2.SHIFT_IN),
									#	CONCAT(DATE_ADD(c1.TGL, INTERVAL c1.IN_SEQ DAY),' ',c2.SHIFT_OUT))
									#) AS TTL_SHIFT, 
									c2.RENTANG_TENGAH AS TTL_SHIFT,
									c2.SHIFT_ID,c2.SHIFT_NM,
									#IZIN TITTLE
									c1.IZIN_STT,c1.IZIN_STT_NM,c1.IZIN,c1.IZIN_NM,
									#TOLERASI TELAT/PULANG LEBIH AWAL 
									#c2.TOLERANSI_TELAT,c2.TOLERANSI_PULANG,
									#VALIDATION POSITIONIG GPS
									c1.MASUK_LAT,c1.MASUK_LAG,c1.PULANG_LAT,c1.PULANG_LAG,c2.RADIUS,
									#ENABLE/DISABLE POTONGAN
									c1.STT_TELAT AS ACTIVE_TELAT,c1.STT_PULANG AS ACTIVE_PULANG,c1.STT_IZIN AS ACTIVE_IZIN,		
									c1.UPAH_HARIAN,
									#GROUP ID SEARCH VALIDATION
									c1.IN_ABSENID,c1.OUT_ABSENID,c1.ACCESS_GROUP,c1.STORE_ID,c1.KARYAWAN_ID,c1.IN_SEQ,SHIFT_SEQ,c1.TGL
								FROM
								(
									SELECT
										(CASE WHEN b2.IN_ABSENID IS NOT NULL THEN b2.IN_ABSENID ELSE '0' END) AS IN_ABSENID,
										(CASE WHEN b2.OUT_ABSENID IS NOT NULL THEN b2.OUT_ABSENID ELSE '0' END) AS OUT_ABSENID,
										(CASE WHEN b1.ACCESS_GROUP THEN b1.ACCESS_GROUP ELSE b2.ACCESS_GROUP END) AS ACCESS_GROUP,
										(CASE WHEN b1.STORE_ID THEN b1.STORE_ID ELSE b2.STORE_ID END) AS STORE_ID,
										(CASE WHEN b1.KARYAWAN_ID THEN b1.KARYAWAN_ID ELSE b2.KARYAWAN_ID END) AS KARYAWAN_ID,
										CONCAT((CASE WHEN b1.NAMA_DPN IS NOT NULL THEN b1.NAMA_DPN ELSE '' END),' ',
													 (CASE WHEN b1.NAMA_TGH IS NOT NULL THEN b1.NAMA_TGH ELSE '' END),' ',
													 (CASE WHEN b1.NAMA_BLK IS NOT NULL THEN b1.NAMA_BLK ELSE '' END)
										)AS KARYAWAN,
										b1.UPAH_HARIAN,b1.STT_POT_TELAT AS STT_TELAT,b1.STT_POT_PULANG AS STT_PULANG,b1.STT_IZIN,
										b2.TGL,b2.WAKTU_MASUK,b2.WAKTU_KELUAR,(CASE WHEN b2.WAKTU_MASUK >= b2.WAKTU_KELUAR THEN 1 ELSE 0 END) AS IN_SEQ,
										b2.IZIN,b2.IZIN_NM,b2.IZIN_STT,b2.IZIN_STT_NM,b2.MASUK_LAT,b2.MASUK_LAG,b2.PULANG_LAT,b2.PULANG_LAG
									FROM karyawan b1
									RIGHT JOIN	
									 ( SELECT 								
											 a1.ACCESS_GROUP,a1.STORE_ID,a1.KARYAWAN_ID,a1.TGL,a1.WAKTU_MASUK,a1.WAKTU_KELUAR,IN_ABSENID,OUT_ABSENID,
											 MAX(CASE WHEN a1.LOG='IZIN' THEN a1.IZIN_LOG ELSE '0' END) AS IZIN,
											 MAX(CASE WHEN a1.LOG='IZIN' THEN a1.LOG_NM ELSE 'NORMAL' END) AS IZIN_NM,
											 MAX(CASE WHEN a1.LOG='IZIN' THEN a1.IZIN_STT ELSE 0 END) AS IZIN_STT,
											 MAX(CASE WHEN a1.LOG='IZIN' THEN a1.IZIN_STT_NM ELSE 'NORMAL' END) AS IZIN_STT_NM,
											 MIN(CASE WHEN a1.LOG=0 THEN a1.LAT END) AS MASUK_LAT,MIN(CASE WHEN a1.LOG=0 THEN a1.LAG END) AS MASUK_LAG,
											 MIN(CASE WHEN a1.LOG=1 THEN a1.LAT END) AS PULANG_LAT,MIN(CASE WHEN a1.LOG=1 THEN a1.LAG END) AS PULANG_LAG
										FROM
										 (
											(
												SELECT ABSEN_ID,ACCESS_GROUP,STORE_ID,KARYAWAN_ID,
															(CASE WHEN STATUS=0 THEN ABSEN_ID END) AS IN_ABSENID,
													  (CASE WHEN STATUS=1 THEN ABSEN_ID END) AS OUT_ABSENID,
															TGL,
															(CASE WHEN STATUS=0 THEN MIN(WAKTU) ELSE NULL END) WAKTU_MASUK,
															MAX(CASE WHEN STATUS=1 THEN WAKTU ELSE NULL END) WAKTU_KELUAR,
															STATUS AS LOG,'ABSEN' AS IZIN_LOG,
															(CASE WHEN STATUS=0 THEN 'IN' ELSE 'OUT' END) AS LOG_NM, '0' AS IZIN_STT,'NORMAL' AS IZIN_STT_NM,
															LATITUDE AS LAT,LONGITUDE AS LAG
												FROM hrd_absen
												WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND 
														STORE_ID='".$val['STORE_ID']."' AND
														(TGL BETWEEN '".$tgl1."' AND '".$tgl2."')
												GROUP BY ACCESS_GROUP,STORE_ID,KARYAWAN_ID,TGL
												ORDER BY STATUS ASC
											) 
											UNION 
											(
												SELECT '0' AS ABSEN_ID,x1.ACCESS_GROUP,x1.STORE_ID,x1.KARYAWAN_ID,
														 '' as IN_ABSENID,'' AS OUT_ABSENID,
														x1.TGL,x1.WAKTU AS WAKTU_MASUK,'' AS WAKTU_KELUAR,
														'IZIN' AS LOG,x1.IZIN_ID AS IZIN_LOG,
														x1.IZIN_NM AS LOG_NM, x1.IZIN_STT,x1.IZIN_STT_NM,'0,0' AS LAT,'0,0' AS LAG
												FROM hrd_absen_izin x1
												WHERE x1.ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND 
														x1.STORE_ID='".$val['STORE_ID']."' AND
														(x1.TGL BETWEEN '".$tgl1."' AND '".$tgl2."') 
											) 
										) a1
										GROUP BY a1.ACCESS_GROUP,a1.STORE_ID,a1.TGL
									) b2 ON b2.ACCESS_GROUP=b1.ACCESS_GROUP AND b2.STORE_ID=b1.STORE_ID AND b2.KARYAWAN_ID=b1.KARYAWAN_ID
									WHERE b1.ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND b1.STORE_ID='".$val['STORE_ID']."' 
								) c1 
								LEFT JOIN 
								(
									SELECT 
										ACCESS_GROUP,STORE_ID,SHIFT_ID,SHIFT_NM,
										RENTANG_BAWAH,RENTANG_ATAS,RENTANG_TENGAH,
										SHIFT_IN_BATAS_BAWAH,SHIFT_IN_BATAS_ATAS,SHIFT_IN_BATAS_SEQ,
										SHIFT_IN,SHIFT_SEQ,SHIFT_OUT,
										RADIUS_KOORDINAT AS RADIUS,TOLERANSI_TELAT,TOLERANSI_PULANG
									FROM hrd_setting_jamkerja
									WHERE ACCESS_GROUP='".$val['ACCESS_GROUP']."' AND STORE_ID='".$val['STORE_ID']."' 
								) c2 on c2.ACCESS_GROUP=c1.ACCESS_GROUP AND c2.STORE_ID=c1.STORE_ID AND 
                  (
										CONCAT(c1.TGl,' ',c1.WAKTU_MASUK) BETWEEN 
										CONCAT(DATE_SUB(c1.TGl, INTERVAL SHIFT_IN_BATAS_SEQ DAY),' ',c2.SHIFT_IN_BATAS_BAWAH) AND 
										CONCAT(c1.TGl,' ',c2.SHIFT_IN_BATAS_ATAS)
									)									
							) d1 
						) e1
					) f1 
					LEFT JOIN hrd_setting_pot f2 ON f2.ID=f1.ID_TELAT
					LEFT JOIN hrd_setting_pot f3 ON f3.ID=f1.ID_AWALPULANG
					LEFT JOIN hrd_setting_pot f4 ON f4.ID=f1.ID_LEMBUR
					LEFT JOIN hrd_absen_rekap g1 ON g1.ACCESS_GROUP=f1.ACCESS_GROUP AND g1.STORE_ID=f1.STORE_ID AND g1.TGL=f1.TGL
					ON DUPLICATE KEY UPDATE
					WAKTU_MASUK=f1.WAKTU_MASUK,WAKTU_KELUAR=f1.WAKTU_KELUAR,SHIFT_ID=f1.SHIFT_ID,SHIFT_NM=f1.SHIFT_NM,SHIFT_IN=f1.SHIFT_IN,SHIFT_OUT=f1.SHIFT_OUT,
					SHIFT_TELAT=f1.SHIFT_TELAT,SHIFT_PULANG=f1.SHIFT_PULANG,SHIFT_RADIUS=f1.RADIUS,SELISIH_TELAT=f1.SELISIH_TELAT,
					SELISIH_AWALPULANG=f1.SELISIH_AWALPULANG,KELEBIHAN_WAKTU=f1.KELEBIHAN_WAKTU,IZIN_STT=f1.IZIN_STT,IZIN_STT_NM=f1.IZIN_STT_NM,IZIN=f1.IZIN_NM=f1.IZIN_NM,
					MASUK_LAT=f1.MASUK_LAT,MASUK_LAG=f1.MASUK_LAG,MASUK_RADIUS='',PULANG_LAT=f1.PULANG_LAT,PULANG_LAG=f1.PULANG_LAG,PULANG_RADIUS='',
					ACTIVE_TELAT=f1.ACTIVE_TELAT,ACTIVE_PULANG=f1.ACTIVE_PULANG,ACTIVE_IZIN=f1.ACTIVE_IZIN,
					POT_PERSEN_TELAT=f2.POT_PERSEN,POT_RUPIAH_TELAT=f2.POT_RUPIAH,POT_JAM_TELAT=f2.POT_JAM2,
					POT_PERSEN_PULANG=f3.POT_PERSEN,POT_RUPIAH_PULANG=f3.POT_RUPIAH,POT_JAM_PULANG=f3.POT_JAM2,
					LEMBUR_PERSEN=f4.POT_PERSEN,LEMBUR_RUPIAH=f4.POT_RUPIAH,LEMBUR_JAM=f4.POT_JAM2,
					UPAH_HARIAN=f1.UPAH_HARIAN,ID_TELAT=f1.ID_TELAT,ID_AWALPULANG=f1.ID_AWALPULANG,
					IN_ABSENID=f1.IN_ABSENID,OUT_ABSENID=f1.OUT_ABSENID,IN_SEQ=f1.IN_SEQ,SEQ_SHIFT=f1.SHIFT_SEQ,ID_LEMBUR=f1.ID_LEMBUR
			";
			
			Yii::$app->db->createCommand($sqlstr1)->execute();
			//==UPDATE==
			$modelUpdate = Cronjob::find()->where(['TABEL'=>$val['TABEL'],'ACCESS_GROUP'=>$val['ACCESS_GROUP'],'STORE_ID'=>$val['STORE_ID']])->one();
			$modelUpdate->STT=0;
			$modelUpdate->UPDATE_CRONJOB=$val['UPDATE_TABEL'];;
			$modelUpdate->save();			
		};
		// print_r($rslt);
		// die();	
	}
}
?>